#!/usr/bin/env node
/**
 * ca-sign.js — Sign a developer's CSR with the CA private key.
 *
 * Usage: node tools/ca-sign.js <developer.csr.json> [output.cert.json]
 *
 * Requires:
 *   tools/ca.key  — CA private key seed (generated by ca-init.js)
 *   tools/ca.json — CA public key (generated by ca-init.js)
 *
 * Outputs:
 *   developer.cert.json — Signed developer certificate
 *
 * No external dependencies. Pure Node.js crypto.
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const TOOLS_DIR = path.resolve(__dirname);
const CA_KEY_PATH = path.join(TOOLS_DIR, 'ca.key');
const CA_JSON_PATH = path.join(TOOLS_DIR, 'ca.json');

function prompt(rl, question, defaultVal) {
    return new Promise((resolve) => {
        const suffix = defaultVal ? ` [${defaultVal}]` : '';
        rl.question(`${question}${suffix}: `, (answer) => {
            resolve(answer.trim() || defaultVal || '');
        });
    });
}

/**
 * Build the canonical payload for signing a certificate.
 * Must match cumod.js buildCertPayload exactly.
 */
const CERT_VERSION = 1;

function buildCertPayload(cert) {
    const canonical = [
        ['v', CERT_VERSION],
        ['developer', cert.developer],
        ['publicKey', cert.publicKey],
        ['organisation', cert.organisation || ''],
        ['website', cert.website || ''],
        ['email', cert.email || ''],
        ['issuedAt', cert.issuedAt],
        ['expiresAt', cert.expiresAt]
    ];
    return JSON.stringify(canonical);
}

async function main() {
    const args = process.argv.slice(2);

    if (args.length < 1) {
        console.log('Usage: node tools/ca-sign.js <developer.csr.json> [output.cert.json]');
        console.log('');
        console.log('Signs a developer CSR with the CA private key.');
        process.exit(1);
    }

    const csrPath = path.resolve(args[0]);
    const outputPath = args[1]
        ? path.resolve(args[1])
        : path.join(path.dirname(csrPath), 'developer.cert.json');

    // Validate inputs
    if (!fs.existsSync(csrPath)) {
        console.error(`Error: CSR file not found: ${csrPath}`);
        process.exit(1);
    }
    if (!fs.existsSync(CA_KEY_PATH)) {
        console.error('Error: CA private key not found (tools/ca.key).');
        console.error('Run "node tools/ca-init.js" first.');
        process.exit(1);
    }
    if (!fs.existsSync(CA_JSON_PATH)) {
        console.error('Error: CA public key not found (tools/ca.json).');
        console.error('Run "node tools/ca-init.js" first.');
        process.exit(1);
    }

    // Load CSR
    const csr = JSON.parse(fs.readFileSync(csrPath, 'utf8'));
    if (!csr.developer || !csr.publicKey) {
        console.error('Error: Invalid CSR — missing developer or publicKey.');
        process.exit(1);
    }

    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

    console.log('');
    console.log('\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557');
    console.log('\u2551   CanvasUI Module CA \u2014 Sign Developer    \u2551');
    console.log('\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d');
    console.log('');
    console.log(`Developer:    ${csr.developer}`);
    console.log(`Public Key:   ${csr.publicKey.slice(0, 16)}...`);
    console.log(`Organisation: ${csr.organisation || '(none)'}`);
    if (csr.website) console.log(`Website:      ${csr.website}`);
    if (csr.email) console.log(`Email:        ${csr.email}`);
    console.log('');

    const validityDays = parseInt(await prompt(rl, 'Certificate validity (days)', '365')) || 365;
    const confirm = await prompt(rl, 'Sign this CSR? (yes/no)', 'yes');

    rl.close();

    if (confirm.toLowerCase() !== 'yes') {
        console.log('Aborted.');
        process.exit(0);
    }

    console.log('');
    console.log('Signing certificate...');

    // Load CA private key
    const seedHex = fs.readFileSync(CA_KEY_PATH, 'utf8').trim();
    const seed = Buffer.from(seedHex, 'hex');

    // Reconstruct Ed25519 private key from seed
    const caPrivateKey = crypto.createPrivateKey({
        key: Buffer.concat([
            Buffer.from('302e020100300506032b657004220420', 'hex'),
            seed
        ]),
        format: 'der',
        type: 'pkcs8'
    });

    // Build certificate
    const now = new Date();
    const expires = new Date(now.getTime() + validityDays * 24 * 60 * 60 * 1000);

    const cert = {
        certVersion: CERT_VERSION,
        developer: csr.developer,
        publicKey: csr.publicKey,
        organisation: csr.organisation || '',
        website: csr.website || '',
        email: csr.email || '',
        issuedAt: now.toISOString(),
        expiresAt: expires.toISOString()
    };

    // Sign the canonical payload
    const payload = buildCertPayload(cert);
    const signature = crypto.sign(null, Buffer.from(payload, 'utf8'), caPrivateKey);
    cert.caSignature = signature.toString('hex');

    // Add non-signed metadata
    if (csr.algorithm) cert.algorithm = csr.algorithm;

    // Write certificate
    fs.writeFileSync(outputPath, JSON.stringify(cert, null, 2), 'utf8');

    console.log('');
    console.log('\u2705 Certificate signed successfully!');
    console.log(`   Output: ${outputPath}`);
    console.log(`   Valid for: ${validityDays} days`);
    console.log(`   Expires: ${expires.toISOString().split('T')[0]}`);
    console.log('');
    console.log('Send this .cert.json file back to the developer.');
    console.log('They will use it with their developer.key to sign modules.');
    console.log('');
}

main().catch(e => {
    console.error('Error:', e.message);
    process.exit(1);
});
